// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABNwhbCX8LM4SXDuFZ2PkNdQGewH7DXtI',
    appId: '1:138549252049:web:189fbba5a549e82f259af0',
    messagingSenderId: '138549252049',
    projectId: 'ajourn-e73e3',
    authDomain: 'ajourn-e73e3.firebaseapp.com',
    storageBucket: 'ajourn-e73e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfCVaZgNDZs2H2KBrPzjBCpSNxVOpxPU',
    appId: '1:138549252049:android:0f05917b08ec47b5259af0',
    messagingSenderId: '138549252049',
    projectId: 'ajourn-e73e3',
    storageBucket: 'ajourn-e73e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1N3nfd0N6eJSPgcH3gqwuHnYxh_4ypbU',
    appId: '1:138549252049:ios:68d4c600369593a1259af0',
    messagingSenderId: '138549252049',
    projectId: 'ajourn-e73e3',
    storageBucket: 'ajourn-e73e3.appspot.com',
    iosClientId: '138549252049-tiao4rb0andirurvseoolbeubu3uepnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ajournApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1N3nfd0N6eJSPgcH3gqwuHnYxh_4ypbU',
    appId: '1:138549252049:ios:68d4c600369593a1259af0',
    messagingSenderId: '138549252049',
    projectId: 'ajourn-e73e3',
    storageBucket: 'ajourn-e73e3.appspot.com',
    iosClientId: '138549252049-tiao4rb0andirurvseoolbeubu3uepnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ajournApp',
  );
}
